name: Upload assets

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node_version: ['14.17.3']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: npm install
      
      - name: Get the version without /refs/tags/
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Replace dots by dashes for filename
        id: get_filename_version
        run: echo ::set-output name=VERSION::${steps.get_version.outputs.VERSION/./-}
      
      - name: Echo
        run: echo ${{ steps.get_filename_version.outputs.VERSION }}